//
//  InflectionRules.swift
//  riidaa
//
//  Created by Pierre on 2025/04/16.
//

import Foundation

public struct Inflection : Sendable {
    
    public let base: String
    public let inflection: String
    public let baseTypes: [WordType]
    public let inflectedTypes: [WordType]
    
    public static let inflectionRules: [InflectionRule: [Inflection]] = [
        .masu: [
            Inflection(base: "る", inflection: "ます", baseTypes: [.v1d], inflectedTypes: [.masu_form]),
            
            Inflection(base: "う", inflection: "います", baseTypes: [.v5d], inflectedTypes: [.masu_form]),
            Inflection(base: "つ", inflection: "ちます", baseTypes: [.v5d], inflectedTypes: [.masu_form]),
            Inflection(base: "る", inflection: "ります", baseTypes: [.v5d], inflectedTypes: [.masu_form]),
            Inflection(base: "ぬ", inflection: "にます", baseTypes: [.v5d], inflectedTypes: [.masu_form]),
            Inflection(base: "ぶ", inflection: "びます", baseTypes: [.v5d], inflectedTypes: [.masu_form]),
            Inflection(base: "む", inflection: "みます", baseTypes: [.v5d], inflectedTypes: [.masu_form]),
            Inflection(base: "く", inflection: "きます", baseTypes: [.v5d], inflectedTypes: [.masu_form]),
            Inflection(base: "ぐ", inflection: "ぎます", baseTypes: [.v5d], inflectedTypes: [.masu_form]),
            Inflection(base: "す", inflection: "します", baseTypes: [.v5d], inflectedTypes: [.masu_form]),
            
            Inflection(base: "する", inflection: "します", baseTypes: [.vs], inflectedTypes: [.masu_form]),
            Inflection(base: "為る", inflection: "為ます", baseTypes: [.vs], inflectedTypes: [.masu_form]),
            
            Inflection(base: "くる", inflection: "きます", baseTypes: [.vk], inflectedTypes: [.masu_form]),
            Inflection(base: "来る", inflection: "来ます", baseTypes: [.vk], inflectedTypes: [.masu_form]),
            Inflection(base: "來る", inflection: "來ます", baseTypes: [.vk], inflectedTypes: [.masu_form]),
        ],
        .te: [
            Inflection(base: "い", inflection: "くて", baseTypes: [.adj_i], inflectedTypes: [.te_form]),
            
            Inflection(base: "る", inflection: "て", baseTypes: [.v1], inflectedTypes: [.te_form]),
            
            Inflection(base: "う", inflection: "って", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "つ", inflection: "って", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "る", inflection: "って", baseTypes: [.v5], inflectedTypes: [.te_form]),
            
            Inflection(base: "ぬ", inflection: "んで", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "ぶ", inflection: "んで", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "む", inflection: "んで", baseTypes: [.v5], inflectedTypes: [.te_form]),
            
            Inflection(base: "く", inflection: "いて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "ぐ", inflection: "いで", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "す", inflection: "して", baseTypes: [.v5], inflectedTypes: [.te_form]),
            
            Inflection(base: "ずる", inflection: "じて", baseTypes: [.vz], inflectedTypes: [.te_form]),
            
            Inflection(base: "する", inflection: "して", baseTypes: [.vs], inflectedTypes: [.te_form]),
            Inflection(base: "為る", inflection: "為て", baseTypes: [.vs], inflectedTypes: [.te_form]),
            
            Inflection(base: "くる", inflection: "きて", baseTypes: [.vk], inflectedTypes: [.te_form]),
            Inflection(base: "来る", inflection: "来て", baseTypes: [.vk], inflectedTypes: [.te_form]),
            Inflection(base: "來る", inflection: "來て", baseTypes: [.vk], inflectedTypes: [.te_form]),
            
            Inflection(base: "いく", inflection: "いって", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "行く", inflection: "行って", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "逝く", inflection: "逝って", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "往く", inflection: "往って", baseTypes: [.v5], inflectedTypes: [.te_form]),
            
            Inflection(base: "こう", inflection: "こうて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "とう", inflection: "とうて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "請う", inflection: "請うて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "乞う", inflection: "乞うて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "恋う", inflection: "恋うて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "問う", inflection: "問うて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "訪う", inflection: "訪うて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "宣う", inflection: "宣うて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "曰う", inflection: "曰うて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "給う", inflection: "給うて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "賜う", inflection: "賜うて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "揺蕩う", inflection: "揺蕩うて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            
            Inflection(base: "のたまう", inflection: "のたもうて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "たまう", inflection: "たもうて", baseTypes: [.v5], inflectedTypes: [.te_form]),
            Inflection(base: "たゆたう", inflection: "たゆとうて", baseTypes: [.v5], inflectedTypes: [.te_form]),
        ],
        .iru: [
            Inflection(base: "て", inflection: "ている", baseTypes: [.te_form], inflectedTypes: [.v1]),
            Inflection(base: "て", inflection: "てる", baseTypes: [.te_form], inflectedTypes: [.v1p]),
            
            Inflection(base: "で", inflection: "でいる", baseTypes: [.te_form], inflectedTypes: [.v1]),
            Inflection(base: "で", inflection: "でる", baseTypes: [.te_form], inflectedTypes: [.v1p]),
            
            Inflection(base: "て", inflection: "ておる", baseTypes: [.te_form], inflectedTypes: [.v5]),
            Inflection(base: "で", inflection: "でおる", baseTypes: [.te_form], inflectedTypes: [.v5]),
            Inflection(base: "て", inflection: "とる", baseTypes: [.te_form], inflectedTypes: [.v5]),
            Inflection(base: "ない", inflection: "ないでいる", baseTypes: [.adj_i], inflectedTypes: [.v1]),
        ],
        .ba: [
            Inflection(base: "い", inflection: "ければ", baseTypes: [.adj_i], inflectedTypes: [.ba_form]),
            Inflection(base: "う", inflection: "えば", baseTypes: [.v5], inflectedTypes: [.ba_form]),
            Inflection(base: "つ", inflection: "てば", baseTypes: [.v5], inflectedTypes: [.ba_form]),
            Inflection(base: "る", inflection: "れば", baseTypes: [.v5, .v1, .vk, .vs, .vz], inflectedTypes: [.ba_form]),
            Inflection(base: "ぬ", inflection: "ねば", baseTypes: [.v5], inflectedTypes: [.ba_form]),
            Inflection(base: "ぶ", inflection: "べば", baseTypes: [.v5], inflectedTypes: [.ba_form]),
            Inflection(base: "む", inflection: "めば", baseTypes: [.v5], inflectedTypes: [.ba_form]),
            Inflection(base: "く", inflection: "けば", baseTypes: [.v5], inflectedTypes: [.ba_form]),
            Inflection(base: "ぐ", inflection: "げば", baseTypes: [.v5], inflectedTypes: [.ba_form]),
            Inflection(base: "す", inflection: "せば", baseTypes: [.v5], inflectedTypes: [.ba_form]),
            Inflection(base: "", inflection: "れば", baseTypes: [.masu_form], inflectedTypes: [.ba_form]),
        ],
        .ya: [
            Inflection(base: "れば", inflection: "りゃ", baseTypes: [.ba_form], inflectedTypes: [.ya_form]),
            Inflection(base: "ければ", inflection: "きゃ", baseTypes: [.ba_form], inflectedTypes: [.ya_form]),
            Inflection(base: "えば", inflection: "や", baseTypes: [.ba_form], inflectedTypes: [.ya_form]),
            Inflection(base: "けば", inflection: "きゃ", baseTypes: [.ba_form], inflectedTypes: [.ya_form]),
            Inflection(base: "げば", inflection: "ぎゃ", baseTypes: [.ba_form], inflectedTypes: [.ya_form]),
            Inflection(base: "せば", inflection: "しゃ", baseTypes: [.ba_form], inflectedTypes: [.ya_form]),
            Inflection(base: "てば", inflection: "ちゃ", baseTypes: [.ba_form], inflectedTypes: [.ya_form]),
            Inflection(base: "ねば", inflection: "にゃ", baseTypes: [.ba_form], inflectedTypes: [.ya_form]),
            Inflection(base: "べば", inflection: "びゃ", baseTypes: [.ba_form], inflectedTypes: [.ya_form]),
            Inflection(base: "めば", inflection: "みゃ", baseTypes: [.ba_form], inflectedTypes: [.ya_form]),
        ],
        .cha: [
            Inflection(base: "る", inflection: "ちゃ", baseTypes: [.v1], inflectedTypes: [.v5]),
            Inflection(base: "ぐ", inflection: "いじゃ", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "く", inflection: "いちゃ", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "す", inflection: "しちゃ", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "う", inflection: "っちゃ", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "つ", inflection: "っちゃ", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "る", inflection: "っちゃ", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "ぬ", inflection: "んじゃ", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "ぶ", inflection: "んじゃ", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "む", inflection: "んじゃ", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "ずる", inflection: "じちゃ", baseTypes: [.vz], inflectedTypes: [.v5]),
            Inflection(base: "する", inflection: "しちゃ", baseTypes: [.vs], inflectedTypes: [.v5]),
            Inflection(base: "為る", inflection: "為ちゃ", baseTypes: [.vs], inflectedTypes: [.v5]),
            Inflection(base: "くる", inflection: "きちゃ", baseTypes: [.vk], inflectedTypes: [.v5]),
            Inflection(base: "来る", inflection: "来ちゃ", baseTypes: [.vk], inflectedTypes: [.v5]),
            Inflection(base: "來る", inflection: "來ちゃ", baseTypes: [.vk], inflectedTypes: [.v5]),
        ],
        .chau: [
            Inflection(base: "る", inflection: "ちゃう", baseTypes: [.v1], inflectedTypes: [.v5]),
            Inflection(base: "ぐ", inflection: "いじゃう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "く", inflection: "いちゃう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "す", inflection: "しちゃう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "う", inflection: "っちゃう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "つ", inflection: "っちゃう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "る", inflection: "っちゃう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "ぬ", inflection: "んじゃう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "ぶ", inflection: "んじゃう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "む", inflection: "んじゃう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "ずる", inflection: "じちゃう", baseTypes: [.vz], inflectedTypes: [.v5]),
            Inflection(base: "する", inflection: "しちゃう", baseTypes: [.vs], inflectedTypes: [.v5]),
            Inflection(base: "為る", inflection: "為ちゃう", baseTypes: [.vs], inflectedTypes: [.v5]),
            Inflection(base: "くる", inflection: "きちゃう", baseTypes: [.vk], inflectedTypes: [.v5]),
            Inflection(base: "来る", inflection: "来ちゃう", baseTypes: [.vk], inflectedTypes: [.v5]),
            Inflection(base: "來る", inflection: "來ちゃう", baseTypes: [.vk], inflectedTypes: [.v5]),
        ],
        .chimau: [
            Inflection(base: "る", inflection: "ちまう", baseTypes: [.v1], inflectedTypes: [.v5]),
            Inflection(base: "ぐ", inflection: "いじまう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "く", inflection: "いちまう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "す", inflection: "しちまう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "う", inflection: "っちまう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "ぬ", inflection: "んじまう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "ぶ", inflection: "んじまう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "む", inflection: "んじまう", baseTypes: [.v5], inflectedTypes: [.v5]),
            Inflection(base: "ずる", inflection: "じちまう", baseTypes: [.vz], inflectedTypes: [.v5]),
            Inflection(base: "する", inflection: "しちまう", baseTypes: [.vs], inflectedTypes: [.v5]),
            Inflection(base: "為る", inflection: "為ちまう", baseTypes: [.vs], inflectedTypes: [.v5]),
            Inflection(base: "くる", inflection: "きちまう", baseTypes: [.vk], inflectedTypes: [.v5]),
            Inflection(base: "来る", inflection: "来ちまう", baseTypes: [.vk], inflectedTypes: [.v5]),
            Inflection(base: "來る", inflection: "來ちまう", baseTypes: [.vk], inflectedTypes: [.v5]),
        ],
        .shimau: [
            Inflection(base: "て", inflection: "てしまう", baseTypes: [.te_form], inflectedTypes: [.v5]),
            Inflection(base: "で", inflection: "でしまう", baseTypes: [.te_form], inflectedTypes: [.v5]),
        ],
        .nasai: [
            Inflection(base: "る", inflection: "なさい", baseTypes: [.v1], inflectedTypes: [.nasai_form]),
            Inflection(base: "う", inflection: "いなさい", baseTypes: [.v5], inflectedTypes: [.nasai_form]),
            Inflection(base: "く", inflection: "きなさい", baseTypes: [.v5], inflectedTypes: [.nasai_form]),
            Inflection(base: "す", inflection: "しなさい", baseTypes: [.v5], inflectedTypes: [.nasai_form]),
            Inflection(base: "つ", inflection: "ちなさい", baseTypes: [.v5], inflectedTypes: [.nasai_form]),
            Inflection(base: "ぬ", inflection: "になさい", baseTypes: [.v5], inflectedTypes: [.nasai_form]),
            Inflection(base: "ぶ", inflection: "びなさい", baseTypes: [.v5], inflectedTypes: [.nasai_form]),
            Inflection(base: "む", inflection: "みなさい", baseTypes: [.v5], inflectedTypes: [.nasai_form]),
            Inflection(base: "る", inflection: "りなさい", baseTypes: [.v5], inflectedTypes: [.nasai_form]),
            Inflection(base: "ずる", inflection: "じなさい", baseTypes: [.vz], inflectedTypes: [.nasai_form]),
            Inflection(base: "する", inflection: "しなさい", baseTypes: [.vs], inflectedTypes: [.nasai_form]),
            Inflection(base: "為る", inflection: "為なさい", baseTypes: [.vs], inflectedTypes: [.nasai_form]),
            Inflection(base: "くる", inflection: "きなさい", baseTypes: [.vk], inflectedTypes: [.nasai_form]),
            Inflection(base: "来る", inflection: "来なさい", baseTypes: [.vk], inflectedTypes: [.nasai_form]),
            Inflection(base: "來る", inflection: "來なさい", baseTypes: [.vk], inflectedTypes: [.nasai_form]),
        ],
        .sou: [
            Inflection(base: "い", inflection: "そう", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "る", inflection: "そう", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "いそう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "ちそう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "りそう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "にそう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "びそう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "みそう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "きそう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "ぎそう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "しそう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "じそう", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "しそう", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為そう", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "きそう", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来そう", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來そう", baseTypes: [.vk], inflectedTypes: []),
        ],
        .sugiru: [
            Inflection(base: "い", inflection: "すぎる", baseTypes: [.adj_i], inflectedTypes: [.v1]),
            Inflection(base: "る", inflection: "すぎる", baseTypes: [.v1], inflectedTypes: [.v1]),
            Inflection(base: "う", inflection: "いすぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "つ", inflection: "ちすぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "る", inflection: "りすぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぬ", inflection: "にすぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぶ", inflection: "びすぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "む", inflection: "みすぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "く", inflection: "きすぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぐ", inflection: "ぎすぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "す", inflection: "しすぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ずる", inflection: "じすぎる", baseTypes: [.vz], inflectedTypes: [.v1]),
            Inflection(base: "する", inflection: "しすぎる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "為る", inflection: "為すぎる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "くる", inflection: "きすぎる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "来る", inflection: "来すぎる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "來る", inflection: "來すぎる", baseTypes: [.vk], inflectedTypes: [.v1]),
            
            Inflection(base: "い", inflection: "過ぎる", baseTypes: [.adj_i], inflectedTypes: [.v1]),
            Inflection(base: "る", inflection: "過ぎる", baseTypes: [.v1], inflectedTypes: [.v1]),
            Inflection(base: "う", inflection: "い過ぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "つ", inflection: "ち過ぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "る", inflection: "り過ぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぬ", inflection: "に過ぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぶ", inflection: "び過ぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "む", inflection: "み過ぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "く", inflection: "き過ぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぐ", inflection: "ぎ過ぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "す", inflection: "し過ぎる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ずる", inflection: "じ過ぎる", baseTypes: [.vz], inflectedTypes: [.v1]),
            Inflection(base: "する", inflection: "し過ぎる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "為る", inflection: "為過ぎる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "くる", inflection: "き過ぎる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "来る", inflection: "来過ぎる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "來る", inflection: "來過ぎる", baseTypes: [.vk], inflectedTypes: [.v1]),
        ],
        .ta: [
            Inflection(base: "い", inflection: "かった", baseTypes: [.adj_i], inflectedTypes: [.ta_form]),
            Inflection(base: "る", inflection: "た", baseTypes: [.v1], inflectedTypes: [.ta_form]),
            Inflection(base: "う", inflection: "った", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "つ", inflection: "った", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "る", inflection: "った", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "ぬ", inflection: "んだ", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "ぶ", inflection: "んだ", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "む", inflection: "んだ", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "く", inflection: "いた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "ぐ", inflection: "いだ", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "す", inflection: "した", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "ずる", inflection: "じた", baseTypes: [.vz], inflectedTypes: [.ta_form]),
            Inflection(base: "する", inflection: "した", baseTypes: [.vs], inflectedTypes: [.ta_form]),
            Inflection(base: "為る", inflection: "為た", baseTypes: [.vs], inflectedTypes: [.ta_form]),
            Inflection(base: "くる", inflection: "きた", baseTypes: [.vk], inflectedTypes: [.ta_form]),
            Inflection(base: "来る", inflection: "来た", baseTypes: [.vk], inflectedTypes: [.ta_form]),
            Inflection(base: "來る", inflection: "來た", baseTypes: [.vk], inflectedTypes: [.ta_form]),
            
            
            Inflection(base: "いく", inflection: "いった", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "行く", inflection: "行った", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "逝く", inflection: "逝った", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "往く", inflection: "往った", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            
            Inflection(base: "こう", inflection: "こうた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "とう", inflection: "とうた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "請う", inflection: "請うた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "乞う", inflection: "乞うた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "恋う", inflection: "恋うた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "問う", inflection: "問うた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "訪う", inflection: "訪うた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "宣う", inflection: "宣うた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "曰う", inflection: "曰うた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "給う", inflection: "給うた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "賜う", inflection: "賜うた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "揺蕩う", inflection: "揺蕩うた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            
            Inflection(base: "のたまう", inflection: "のたもうた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "たまう", inflection: "たもうた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            Inflection(base: "たゆたう", inflection: "たゆとうた", baseTypes: [.v5], inflectedTypes: [.ta_form]),
            
            Inflection(base: "ます", inflection: "ました", baseTypes: [.masu_form], inflectedTypes: [.ta_form]),
            Inflection(base: "", inflection: "でした", baseTypes: [.masen_form], inflectedTypes: [.ta_form]),
            Inflection(base: "", inflection: "かった", baseTypes: [.masen_form, .n_form], inflectedTypes: [.ta_form]),
            
            
            Inflection(base: "てる", inflection: "てた", baseTypes: [.v1p], inflectedTypes: [.ta_form]),
        ],
        .negative: [
            Inflection(base: "い", inflection: "くない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "る", inflection: "ない", baseTypes: [.v1], inflectedTypes: [.adj_i]),
            Inflection(base: "う", inflection: "わない", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "く", inflection: "かない", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "ぐ", inflection: "がない", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "す", inflection: "さない", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "つ", inflection: "たない", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "ぬ", inflection: "なない", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "ぶ", inflection: "ばない", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "む", inflection: "まない", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "る", inflection: "らない", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "ずる", inflection: "じない", baseTypes: [.vz], inflectedTypes: [.adj_i]),
            Inflection(base: "する", inflection: "しない", baseTypes: [.vs], inflectedTypes: [.adj_i]),
            Inflection(base: "為る", inflection: "為ない", baseTypes: [.vs], inflectedTypes: [.adj_i]),
            Inflection(base: "くる", inflection: "こない", baseTypes: [.vk], inflectedTypes: [.adj_i]),
            Inflection(base: "来る", inflection: "来ない", baseTypes: [.vk], inflectedTypes: [.adj_i]),
            Inflection(base: "來る", inflection: "來ない", baseTypes: [.vk], inflectedTypes: [.adj_i]),
            Inflection(base: "ます", inflection: "ません", baseTypes: [.masu_form], inflectedTypes: [.masen_form]),
        ],
        .tai: [
            Inflection(base: "る", inflection: "たい", baseTypes: [.v1], inflectedTypes: [.adj_i]),
            Inflection(base: "う", inflection: "いたい", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "く", inflection: "きたい", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "ぐ", inflection: "ぎたい", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "す", inflection: "したい", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "つ", inflection: "ちたい", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "ぬ", inflection: "にたい", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "ぶ", inflection: "びたい", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "む", inflection: "みたい", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "る", inflection: "りたい", baseTypes: [.v5], inflectedTypes: [.adj_i]),
            Inflection(base: "ずる", inflection: "じたい", baseTypes: [.vz], inflectedTypes: [.adj_i]),
            Inflection(base: "する", inflection: "したい", baseTypes: [.vs], inflectedTypes: [.adj_i]),
            Inflection(base: "為る", inflection: "為たい", baseTypes: [.vs], inflectedTypes: [.adj_i]),
            Inflection(base: "くる", inflection: "こたい", baseTypes: [.vk], inflectedTypes: [.adj_i]),
            Inflection(base: "来る", inflection: "来たい", baseTypes: [.vk], inflectedTypes: [.adj_i]),
            Inflection(base: "來る", inflection: "來たい", baseTypes: [.vk], inflectedTypes: [.adj_i]),
        ],
        .tara: [
            Inflection(base: "い", inflection: "かったら", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "る", inflection: "たら", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "ったら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "ったら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "ったら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "んだら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "んだら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "んだら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "いたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "いだら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "したら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "じたら", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "したら", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為たら", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "きたら", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来たら", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來たら", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "ます", inflection: "ましたら", baseTypes: [.masu_form], inflectedTypes: []),
            
            Inflection(base: "いく", inflection: "いったら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "行く", inflection: "行ったら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "逝く", inflection: "逝ったら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "往く", inflection: "往ったら", baseTypes: [.v5], inflectedTypes: []),
            
            Inflection(base: "こう", inflection: "こうたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "とう", inflection: "とうたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "請う", inflection: "請うたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "乞う", inflection: "乞うたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "恋う", inflection: "恋うたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "問う", inflection: "問うたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "訪う", inflection: "訪うたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "宣う", inflection: "宣うたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "曰う", inflection: "曰うたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "給う", inflection: "給うたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "賜う", inflection: "賜うたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "揺蕩う", inflection: "揺蕩うたら", baseTypes: [.v5], inflectedTypes: []),
            
            Inflection(base: "のたまう", inflection: "のたもうたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "たまう", inflection: "たもうたら", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "たゆたう", inflection: "たゆとうたら", baseTypes: [.v5], inflectedTypes: []),
        ],
        .tari: [
            Inflection(base: "い", inflection: "かったり", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "る", inflection: "たり", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "いたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "ちたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "りたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "にたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "びたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "みたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "きたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "ぎたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "したり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "じたり", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "したり", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為たり", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "きたり", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来たり", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來たり", baseTypes: [.vk], inflectedTypes: []),
            
            Inflection(base: "いく", inflection: "いったり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "行く", inflection: "行ったり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "逝く", inflection: "逝ったり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "往く", inflection: "往ったり", baseTypes: [.v5], inflectedTypes: []),
            
            Inflection(base: "こう", inflection: "こうたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "とう", inflection: "とうたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "請う", inflection: "請うたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "乞う", inflection: "乞うたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "恋う", inflection: "恋うたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "問う", inflection: "問うたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "訪う", inflection: "訪うたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "宣う", inflection: "宣うたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "曰う", inflection: "曰うたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "給う", inflection: "給うたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "賜う", inflection: "賜うたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "揺蕩う", inflection: "揺蕩うたり", baseTypes: [.v5], inflectedTypes: []),
            
            Inflection(base: "のたまう", inflection: "のたもうたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "たまう", inflection: "たもうたり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "たゆたう", inflection: "たゆとうたり", baseTypes: [.v5], inflectedTypes: []),
        ],
        .causative: [
            Inflection(base: "る", inflection: "させる", baseTypes: [.v1], inflectedTypes: [.v1]),
            Inflection(base: "う", inflection: "わせる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "つ", inflection: "たせる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "る", inflection: "らせる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぬ", inflection: "なせる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぶ", inflection: "ばせる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "む", inflection: "ませる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "く", inflection: "かせる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぐ", inflection: "がせる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "す", inflection: "させる", baseTypes: [.v5], inflectedTypes: [.v1]),
            
            Inflection(base: "ずる", inflection: "じさせる", baseTypes: [.vz], inflectedTypes: [.v1]),
            Inflection(base: "ずる", inflection: "ぜさせる", baseTypes: [.vz], inflectedTypes: [.v1]),
            Inflection(base: "する", inflection: "させる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "する", inflection: "せさせる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "為る", inflection: "為せる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "為る", inflection: "為させる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "くる", inflection: "こさせる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "来る", inflection: "来させる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "來る", inflection: "來させる", baseTypes: [.vk], inflectedTypes: [.v1]),
        ],
        .short_causative: [
            Inflection(base: "る", inflection: "さす", baseTypes: [.v1], inflectedTypes: [.v5ss]),
            Inflection(base: "う", inflection: "わす", baseTypes: [.v5], inflectedTypes: [.v5sp]),
            Inflection(base: "つ", inflection: "たす", baseTypes: [.v5], inflectedTypes: [.v5sp]),
            Inflection(base: "る", inflection: "らす", baseTypes: [.v5], inflectedTypes: [.v5sp]),
            Inflection(base: "ぬ", inflection: "なす", baseTypes: [.v5], inflectedTypes: [.v5sp]),
            Inflection(base: "ぶ", inflection: "ばす", baseTypes: [.v5], inflectedTypes: [.v5sp]),
            Inflection(base: "む", inflection: "ます", baseTypes: [.v5], inflectedTypes: [.v5sp]),
            Inflection(base: "く", inflection: "かす", baseTypes: [.v5], inflectedTypes: [.v5sp]),
            Inflection(base: "ぐ", inflection: "がす", baseTypes: [.v5], inflectedTypes: [.v5sp]),
            Inflection(base: "す", inflection: "さす", baseTypes: [.v5], inflectedTypes: [.v5ss]),
            
            Inflection(base: "ずる", inflection: "じさす", baseTypes: [.vz], inflectedTypes: [.v5ss]),
            Inflection(base: "ずる", inflection: "ぜさす", baseTypes: [.vz], inflectedTypes: [.v5ss]),
            Inflection(base: "する", inflection: "さす", baseTypes: [.vs], inflectedTypes: [.v5ss]),
            Inflection(base: "為る", inflection: "為す", baseTypes: [.vs], inflectedTypes: [.v5ss]),
            Inflection(base: "くる", inflection: "こさす", baseTypes: [.vk], inflectedTypes: [.v5ss]),
            Inflection(base: "来る", inflection: "来さす", baseTypes: [.vk], inflectedTypes: [.v5ss]),
            Inflection(base: "來る", inflection: "來さす", baseTypes: [.vk], inflectedTypes: [.v5ss]),
        ],
        .ku: [
            Inflection(base: "い", inflection: "く", baseTypes: [.adj_i], inflectedTypes: [.ku_form])
        ],
        .zu: [
            Inflection(base: "る", inflection: "ず", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "わず", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "たず", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "らず", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "なず", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "ばず", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "まず", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "かず", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "がず", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "さず", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "ぜず", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "せず", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為ず", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "こず", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来ず", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來ず", baseTypes: [.vk], inflectedTypes: []),
        ],
        .nu: [
            Inflection(base: "る", inflection: "ぬ", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "わぬ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "たぬ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "らぬ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "なぬ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "ばぬ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "まぬ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "かぬ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "がぬ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "さぬ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "ぜぬ", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "せぬ", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為ぬ", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "こぬ", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来ぬ", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來ぬ", baseTypes: [.vk], inflectedTypes: []),
        ],
        .n: [
            Inflection(base: "る", inflection: "ん", baseTypes: [.v1], inflectedTypes: [.n_form]),
            Inflection(base: "う", inflection: "わん", baseTypes: [.v5], inflectedTypes: [.n_form]),
            Inflection(base: "つ", inflection: "たん", baseTypes: [.v5], inflectedTypes: [.n_form]),
            Inflection(base: "る", inflection: "らん", baseTypes: [.v5], inflectedTypes: [.n_form]),
            Inflection(base: "ぬ", inflection: "なん", baseTypes: [.v5], inflectedTypes: [.n_form]),
            Inflection(base: "ぶ", inflection: "ばん", baseTypes: [.v5], inflectedTypes: [.n_form]),
            Inflection(base: "む", inflection: "まん", baseTypes: [.v5], inflectedTypes: [.n_form]),
            Inflection(base: "く", inflection: "かん", baseTypes: [.v5], inflectedTypes: [.n_form]),
            Inflection(base: "ぐ", inflection: "がん", baseTypes: [.v5], inflectedTypes: [.n_form]),
            Inflection(base: "す", inflection: "さん", baseTypes: [.v5], inflectedTypes: [.n_form]),
            Inflection(base: "ずる", inflection: "ぜん", baseTypes: [.vz], inflectedTypes: [.n_form]),
            Inflection(base: "する", inflection: "せん", baseTypes: [.vs], inflectedTypes: [.n_form]),
            Inflection(base: "為る", inflection: "為ん", baseTypes: [.vs], inflectedTypes: [.n_form]),
            Inflection(base: "くる", inflection: "こん", baseTypes: [.vk], inflectedTypes: [.n_form]),
            Inflection(base: "来る", inflection: "来ん", baseTypes: [.vk], inflectedTypes: [.n_form]),
            Inflection(base: "來る", inflection: "來ん", baseTypes: [.vk], inflectedTypes: [.n_form]),
        ],
        .nbakari: [
            Inflection(base: "る", inflection: "んばかり", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "わんばかり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "たんばかり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "らんばかり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "なんばかり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "ばんばかり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "まんばかり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "かんばかり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "がんばかり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "さんばかり", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "ぜんばかり", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "せんばかり", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為んばかり", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "こんばかり", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来んばかり", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來んばかり", baseTypes: [.vk], inflectedTypes: []),
        ],
        .ntosuru: [
            Inflection(base: "る", inflection: "んとする", baseTypes: [.v1], inflectedTypes: [.vs]),
            Inflection(base: "う", inflection: "わんとする", baseTypes: [.v5], inflectedTypes: [.vs]),
            Inflection(base: "つ", inflection: "たんとする", baseTypes: [.v5], inflectedTypes: [.vs]),
            Inflection(base: "る", inflection: "らんとする", baseTypes: [.v5], inflectedTypes: [.vs]),
            Inflection(base: "ぬ", inflection: "なんとする", baseTypes: [.v5], inflectedTypes: [.vs]),
            Inflection(base: "ぶ", inflection: "ばんとする", baseTypes: [.v5], inflectedTypes: [.vs]),
            Inflection(base: "む", inflection: "まんとする", baseTypes: [.v5], inflectedTypes: [.vs]),
            Inflection(base: "く", inflection: "かんとする", baseTypes: [.v5], inflectedTypes: [.vs]),
            Inflection(base: "ぐ", inflection: "がんとする", baseTypes: [.v5], inflectedTypes: [.vs]),
            Inflection(base: "す", inflection: "さんとする", baseTypes: [.v5], inflectedTypes: [.vs]),
            Inflection(base: "ずる", inflection: "ぜんとする", baseTypes: [.vz], inflectedTypes: [.vs]),
            Inflection(base: "する", inflection: "せんとする", baseTypes: [.vs], inflectedTypes: [.vs]),
            Inflection(base: "為る", inflection: "為んとする", baseTypes: [.vs], inflectedTypes: [.vs]),
            Inflection(base: "くる", inflection: "こんとする", baseTypes: [.vk], inflectedTypes: [.vs]),
            Inflection(base: "来る", inflection: "来んとする", baseTypes: [.vk], inflectedTypes: [.vs]),
            Inflection(base: "來る", inflection: "來んとする", baseTypes: [.vk], inflectedTypes: [.vs]),
        ],
        .mu: [
            Inflection(base: "る", inflection: "む", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "わむ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "たむ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "らむ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "なむ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "ばむ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "まむ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "かむ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "がむ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "さむ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "ぜむ", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "せむ", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為む", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "こむ", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来む", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來む", baseTypes: [.vk], inflectedTypes: []),
        ],
        .zaru: [
            Inflection(base: "る", inflection: "ざる", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "わざる", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "たざる", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "らざる", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "なざる", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "ばざる", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "まざる", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "かざる", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "がざる", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "さざる", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "ぜざる", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "せざる", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為ざる", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "こざる", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来ざる", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來ざる", baseTypes: [.vk], inflectedTypes: []),
        ],
        .neba: [
            Inflection(base: "る", inflection: "ねば", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "わねば", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "たねば", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "らねば", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "なねば", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "ばねば", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "まねば", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "かねば", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "がねば", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "さねば", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "ぜねば", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "せねば", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為ねば", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "こねば", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来ねば", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來ねば", baseTypes: [.vk], inflectedTypes: []),
        ],
        .imperative: [
            Inflection(base: "る", inflection: "ろ", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "る", inflection: "よ", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "え", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "て", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "れ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "ね", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "べ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "め", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "け", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "げ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "せ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "じろ", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "ぜよ", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "しろ", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "する", inflection: "せよ", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為ろ", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為よ", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "こい", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来い", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來い", baseTypes: [.vk], inflectedTypes: []),
        ],
        .continuative: [
            Inflection(base: "いる", inflection: "い", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "える", inflection: "え", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "きる", inflection: "き", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "ける", inflection: "け", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "ぎる", inflection: "ぎ", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "げる", inflection: "げ", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "せる", inflection: "せ", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "じる", inflection: "じ", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "ぜる", inflection: "ぜ", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "ちる", inflection: "ち", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "てる", inflection: "て", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "でる", inflection: "で", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "にる", inflection: "に", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "ねる", inflection: "ね", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "ひる", inflection: "ひ", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "びる", inflection: "び", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "へる", inflection: "へ", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "べる", inflection: "べ", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "みる", inflection: "み", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "める", inflection: "め", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "りる", inflection: "り", baseTypes: [.v1d], inflectedTypes: []),
            Inflection(base: "れる", inflection: "れ", baseTypes: [.v1d], inflectedTypes: []),
            
            Inflection(base: "う", inflection: "い", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "ち", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "り", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "に", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "び", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "み", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "き", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "ぎ", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "し", baseTypes: [.v5], inflectedTypes: []),
            
            Inflection(base: "ずる", inflection: "ず", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "し", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "き", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來", baseTypes: [.vk], inflectedTypes: []),
        ],
        .sa: [
            Inflection(base: "い", inflection: "さ", baseTypes: [.adj_i], inflectedTypes: [])
        ],
        .passive: [
            Inflection(base: "う", inflection: "われる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "つ", inflection: "たれる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "る", inflection: "られる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぬ", inflection: "なれる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぶ", inflection: "ばれる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "む", inflection: "まれる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "く", inflection: "かれる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "ぐ", inflection: "がれる", baseTypes: [.v5], inflectedTypes: [.v1]),
            Inflection(base: "す", inflection: "される", baseTypes: [.v5d, .v5sp], inflectedTypes: [.v1]),
            
            Inflection(base: "ずる", inflection: "じされる", baseTypes: [.vz], inflectedTypes: [.v1]),
            Inflection(base: "ずる", inflection: "ぜされる", baseTypes: [.vz], inflectedTypes: [.v1]),
            Inflection(base: "する", inflection: "される", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "為る", inflection: "為れる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "くる", inflection: "こられる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "来る", inflection: "来られる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "來る", inflection: "來られる", baseTypes: [.vk], inflectedTypes: [.v1]),
        ],
        .potential: [
            Inflection(base: "う", inflection: "える", baseTypes: [.v5d], inflectedTypes: [.v1]),
            Inflection(base: "つ", inflection: "てる", baseTypes: [.v5d], inflectedTypes: [.v1]),
            Inflection(base: "る", inflection: "れる", baseTypes: [.v5d], inflectedTypes: [.v1]),
            Inflection(base: "ぬ", inflection: "ねる", baseTypes: [.v5d], inflectedTypes: [.v1]),
            Inflection(base: "ぶ", inflection: "べる", baseTypes: [.v5d], inflectedTypes: [.v1]),
            Inflection(base: "む", inflection: "める", baseTypes: [.v5d], inflectedTypes: [.v1]),
            Inflection(base: "く", inflection: "ける", baseTypes: [.v5d], inflectedTypes: [.v1]),
            Inflection(base: "ぐ", inflection: "げる", baseTypes: [.v5d], inflectedTypes: [.v1]),
            Inflection(base: "す", inflection: "せる", baseTypes: [.v5d], inflectedTypes: [.v1]),
            
            Inflection(base: "する", inflection: "できる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "為る", inflection: "出来る", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "くる", inflection: "これる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "来る", inflection: "来れる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "來る", inflection: "來れる", baseTypes: [.vk], inflectedTypes: [.v1]),
        ],
        .potential_passive: [
            Inflection(base: "る", inflection: "られる", baseTypes: [.v1], inflectedTypes: [.v1]),
            Inflection(base: "ずる", inflection: "ざれる", baseTypes: [.vz], inflectedTypes: [.v1]),
            Inflection(base: "ずる", inflection: "ぜられる", baseTypes: [.vz], inflectedTypes: [.v1]),
            Inflection(base: "する", inflection: "せられる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "為る", inflection: "為られる", baseTypes: [.vs], inflectedTypes: [.v1]),
            Inflection(base: "くる", inflection: "こられる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "来る", inflection: "来られる", baseTypes: [.vk], inflectedTypes: [.v1]),
            Inflection(base: "來る", inflection: "來られる", baseTypes: [.vk], inflectedTypes: [.v1]),
        ],
        .volitional: [
            Inflection(base: "る", inflection: "よう", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "おう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "とう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "ろう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "のう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "ぼう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "もう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "こう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "ごう", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "そう", baseTypes: [.v5], inflectedTypes: []),
            
            Inflection(base: "ずる", inflection: "じよう", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "しよう", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為よう", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "こよう", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来よう", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來よう", baseTypes: [.vk], inflectedTypes: []),
            
            Inflection(base: "ます", inflection: "ましょう", baseTypes: [.masu_form], inflectedTypes: []),
            Inflection(base: "い", inflection: "かろう", baseTypes: [.adj_i], inflectedTypes: []),
        ],
        .volitional_slang: [
            Inflection(base: "る", inflection: "よっか", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "う", inflection: "おっか", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "つ", inflection: "とっか", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "る", inflection: "ろっか", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぬ", inflection: "のっか", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぶ", inflection: "ぼっか", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "む", inflection: "もっか", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "く", inflection: "こっか", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "ぐ", inflection: "ごっか", baseTypes: [.v5], inflectedTypes: []),
            Inflection(base: "す", inflection: "そっか", baseTypes: [.v5], inflectedTypes: []),
            
            Inflection(base: "ずる", inflection: "じよっか", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "しよっか", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為よっか", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "こよっか", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来よっか", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來よっか", baseTypes: [.vk], inflectedTypes: []),
            
            Inflection(base: "ます", inflection: "ましょっか", baseTypes: [.masu_form], inflectedTypes: []),
            Inflection(base: "い", inflection: "かろっか", baseTypes: [.adj_i], inflectedTypes: []),
        ],
        .mai: [
            Inflection(base: "", inflection: "まい", baseTypes: [.v], inflectedTypes: []),
            Inflection(base: "る", inflection: "まい", baseTypes: [.v1], inflectedTypes: []),
            Inflection(base: "", inflection: "まい", baseTypes: [.masu_form], inflectedTypes: []),
            Inflection(base: "ずる", inflection: "じまい", baseTypes: [.vz], inflectedTypes: []),
            Inflection(base: "する", inflection: "しまい", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "為る", inflection: "為まい", baseTypes: [.vs], inflectedTypes: []),
            Inflection(base: "くる", inflection: "こまい", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "来る", inflection: "来まい", baseTypes: [.vk], inflectedTypes: []),
            Inflection(base: "來る", inflection: "來まい", baseTypes: [.vk], inflectedTypes: []),
        ],
        .oku: [
            Inflection(base: "て", inflection: "ておく", baseTypes: [.te_form], inflectedTypes: [.v5]),
            Inflection(base: "で", inflection: "でおく", baseTypes: [.te_form], inflectedTypes: [.v5]),
            
            Inflection(base: "て", inflection: "とく", baseTypes: [.te_form], inflectedTypes: [.v5]),
            Inflection(base: "で", inflection: "どく", baseTypes: [.te_form], inflectedTypes: [.v5]),
            
            Inflection(base: "ない", inflection: "ないでおく", baseTypes: [.adj_i], inflectedTypes: [.v5]),
            Inflection(base: "ない", inflection: "ないどく", baseTypes: [.adj_i], inflectedTypes: [.v5]),
        ],
        .ki: [
            Inflection(base: "い", inflection: "き", baseTypes: [.adj_i], inflectedTypes: [])
        ],
        .ge: [
            Inflection(base: "い", inflection: "げ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "い", inflection: "気", baseTypes: [.adj_i], inflectedTypes: [])
        ],
        .garu: [
            Inflection(base: "い", inflection: "がる", baseTypes: [.adj_i], inflectedTypes: [.v5])
        ],
        .e: [
            Inflection(base: "ない", inflection: "ねえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "むい", inflection: "めえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "むい", inflection: "みい", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "つい", inflection: "ちぇえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "つい", inflection: "ちい", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "すい", inflection: "せえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "いい", inflection: "ええ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "わい", inflection: "ええ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "よい", inflection: "ええ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "よい", inflection: "いぇえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "わい", inflection: "うぇえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "かい", inflection: "けえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "がい", inflection: "げえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ごい", inflection: "げえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "さい", inflection: "せえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "まい", inflection: "めえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ずい", inflection: "ぜえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ずい", inflection: "っぜえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "らい", inflection: "れえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "らい", inflection: "れえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ちゃい", inflection: "ちぇえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "どい", inflection: "でえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "れい", inflection: "れえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ばい", inflection: "べえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "たい", inflection: "てえ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ない", inflection: "ねぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "むい", inflection: "めぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "むい", inflection: "みぃ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "つい", inflection: "ちぃ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "すい", inflection: "せぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "かい", inflection: "けぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "がい", inflection: "げぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ごい", inflection: "げぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "さい", inflection: "せぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "まい", inflection: "めぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ずい", inflection: "ぜぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ずい", inflection: "っぜぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "らい", inflection: "れぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "どい", inflection: "でぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "れい", inflection: "れぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ばい", inflection: "べぇ", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "たい", inflection: "てぇ", baseTypes: [.adj_i], inflectedTypes: []),
        ],
        .n_slang: [
            Inflection(base: "りなさい", inflection: "んなさい", baseTypes: [.nasai_form], inflectedTypes: []),
            Inflection(base: "られない", inflection: "らんない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "らない", inflection: "んない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "らなきゃ", inflection: "んなきゃ", baseTypes: [.ya_form], inflectedTypes: []),
            Inflection(base: "れなきゃ", inflection: "んなきゃ", baseTypes: [.ya_form], inflectedTypes: []),
        ],
        .imperative_negative_slang: [
            Inflection(base: "る", inflection: "んな", baseTypes: [.v], inflectedTypes: []),
        ],
        .kansai_negative: [
            Inflection(base: "ない", inflection: "へん", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "ない", inflection: "ひん", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "しない", inflection: "せえへん", baseTypes: [.adj_i], inflectedTypes: []),
            Inflection(base: "なかった", inflection: "へんかった", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "なかった", inflection: "ひんかった", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "ってない", inflection: "うてへん", baseTypes: [.adj_i], inflectedTypes: []),
        ],
        .kansai_te: [
            Inflection(base: "って", inflection: "うて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "あって", inflection: "おうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "かって", inflection: "こうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "がって", inflection: "ごうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "さって", inflection: "そうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "ざって", inflection: "ぞうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "たって", inflection: "とうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "だって", inflection: "どうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "なって", inflection: "のうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "はって", inflection: "ほうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "ばって", inflection: "ぼうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "まって", inflection: "もうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "らって", inflection: "ろうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "やって", inflection: "ようて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "いって", inflection: "ゆうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
        ],
        .kansai_ta: [
            Inflection(base: "った", inflection: "うた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "あった", inflection: "おうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "かった", inflection: "こうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "がった", inflection: "ごうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "さった", inflection: "そうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "ざった", inflection: "ぞうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "たった", inflection: "とうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "だった", inflection: "どうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "なった", inflection: "のうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "はった", inflection: "ほうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "ばった", inflection: "ぼうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "まった", inflection: "もうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "らった", inflection: "ろうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "やった", inflection: "ようた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
            Inflection(base: "いった", inflection: "ゆうた", baseTypes: [.ta_form], inflectedTypes: [.ta_form]),
        ],
        .kansai_tara: [
            Inflection(base: "ったら", inflection: "うたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "あったら", inflection: "おうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "かったら", inflection: "こうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "がったら", inflection: "ごうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "さったら", inflection: "そうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "ざったら", inflection: "ぞうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "たったら", inflection: "とうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "だったら", inflection: "どうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "なったら", inflection: "のうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "はったら", inflection: "ほうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "ばったら", inflection: "ぼうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "まったら", inflection: "もうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "らったら", inflection: "ろうたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "やったら", inflection: "ようたら", baseTypes: [], inflectedTypes: []),
            Inflection(base: "いったら", inflection: "ゆうたら", baseTypes: [], inflectedTypes: []),
        ],
        .kansai_tari: [
            Inflection(base: "ったり", inflection: "うたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "あったり", inflection: "おうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "かったり", inflection: "こうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "がったり", inflection: "ごうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "さったり", inflection: "そうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "ざったり", inflection: "ぞうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "たったり", inflection: "とうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "だったり", inflection: "どうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "なったり", inflection: "のうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "はったり", inflection: "ほうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "ばったり", inflection: "ぼうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "まったり", inflection: "もうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "らったり", inflection: "ろうたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "やったり", inflection: "ようたり", baseTypes: [], inflectedTypes: []),
            Inflection(base: "いったり", inflection: "ゆうたり", baseTypes: [], inflectedTypes: []),
        ],
        .kansai_ku: [
            Inflection(base: "く", inflection: "う", baseTypes: [.ku_form], inflectedTypes: []),
            Inflection(base: "かく", inflection: "こう", baseTypes: [.ku_form], inflectedTypes: []),
            Inflection(base: "がく", inflection: "ごう", baseTypes: [.ku_form], inflectedTypes: []),
            Inflection(base: "さく", inflection: "そう", baseTypes: [.ku_form], inflectedTypes: []),
            Inflection(base: "たく", inflection: "とう", baseTypes: [.ku_form], inflectedTypes: []),
            Inflection(base: "なく", inflection: "のう", baseTypes: [.ku_form], inflectedTypes: []),
            Inflection(base: "ばく", inflection: "ぼう", baseTypes: [.ku_form], inflectedTypes: []),
            Inflection(base: "まく", inflection: "もう", baseTypes: [.ku_form], inflectedTypes: []),
            Inflection(base: "らく", inflection: "ろう", baseTypes: [.ku_form], inflectedTypes: []),
            Inflection(base: "よく", inflection: "よう", baseTypes: [.ku_form], inflectedTypes: []),
            Inflection(base: "しく", inflection: "しゅう", baseTypes: [.ku_form], inflectedTypes: []),
        ],
        .kansai_adj_te: [
            Inflection(base: "くて", inflection: "うて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "かくて", inflection: "こうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "がくて", inflection: "ごうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "さくて", inflection: "そうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "たくて", inflection: "とうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "なくて", inflection: "のうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "ばくて", inflection: "ぼうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "まくて", inflection: "もうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "らくて", inflection: "ろうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "よくて", inflection: "ようて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
            Inflection(base: "しくて", inflection: "しゅうて", baseTypes: [.te_form], inflectedTypes: [.te_form]),
        ],
        .kansai_adj_negative: [
            Inflection(base: "くない", inflection: "うない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "かくない", inflection: "こうない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "がくない", inflection: "ごうない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "さくない", inflection: "そうない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "たくない", inflection: "とうない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "なくない", inflection: "のうない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "ばくない", inflection: "ぼうない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "まくない", inflection: "もうない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "らくない", inflection: "ろうない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "よくない", inflection: "ようない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
            Inflection(base: "しくない", inflection: "しゅうない", baseTypes: [.adj_i], inflectedTypes: [.adj_i]),
        ],
        
    ]
    
    public func match(text: String) -> Bool {
        return text.hasSuffix(self.inflection)
    }
    
    public static func deinflect(text: String) -> [Deinflection] {
        var deinflections: [Deinflection] = [Deinflection(text: text, inflections: [], types: [])]
        
        var i = 0
        while i < deinflections.count {
            let current_deinflection = deinflections[i]
            for (ruleName, inflections) in Inflection.inflectionRules {
                for inflection in inflections {
                    if (current_deinflection.types.isEmpty || current_deinflection.types.inflectionMatch(wl: inflection.inflectedTypes)) && inflection.match(text: current_deinflection.text) {
                        
                        let newText = String(current_deinflection.text.dropLast(inflection.inflection.count)) + inflection.base
                        var newInflections = current_deinflection.inflections
                        newInflections.append(ruleName)
                        let newTypes = inflection.baseTypes
                        
                        deinflections.append(Deinflection(text: newText, inflections: newInflections, types: newTypes))
                    }
                }
            }
            i += 1
        }
        return deinflections.filter({ d in
            d.types.inflectionMatch(wl: [.v, .adj_i])
        })
        
//        return deinflections
    }
    
}
